FROM apache/airflow:2.9.1-python3.11

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    curl \
    && apt-get clean

USER airflow

COPY infra/requirements-airflow.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt