FROM apache/superset:3.1.3

USER root

RUN pip install --no-cache-dir \
    requests \
    boto3 \
    "PyAthena[SQLAlchemy]==3.0.10" \
    "sqlalchemy-trino" 

# Ensure pythonpath dir exists for config pickup
RUN mkdir -p /app/pythonpath

USER superset